application: assets-brandonc-me
version: static
runtime: python27 
api_version: 1
threadsafe: true

default_expiration: "7d"

pagespeed:
  enabled_rewriters:
  - MinifyCss
  - CollapseWhitespace
  - RemoveComments

handlers:
- url: /blog
  static_dir: blog

- url: /.*
  static_files: index.html
  upload: index.html
